<?php
/*
	//Dynamic css, here css value are control from customizer
*/
// Grab the HEX color values from theme options
$nora_accent = get_theme_mod( 'accent_color' );
if ( $nora_accent ) { 

		/*-----------------------------------------------------------------
		 These are dynamic accent color values generated by theme options
		-----------------------------------------------------------------*/

	$nora_dynamic_accent = '#header #toggle i,
		#header #nav li a:hover,
		#header #nav ul a:hover,
		#header #nav ul ul a:hover,
		#header #nav ul li.current-menu-item a,
		#header #nav ul a:hover,
		#header #nav ul ul a:hover,
		#header #nav ul li.current-menu-item a,
		#content article.format-quote .entry-title a:hover blockquote p,
		#sidebar-drawer .widget a,
		.nora_tweet_widget a {
			color: '.esc_html( $nora_accent ).' !important;
			}
			
		a:hover,
		#header .logo a:hover,
		#header #nav li.current_page_item a, 
		#header #nav li.current-menu-parent a,
		#header #nav li.current_page_parent a,
		#content article a.more,
		#content article.format-link .entry-link h3 a:hover,
		.nora_tweet_widget a,
		body.page-template-template-homepage-php #intro a,
		body.page-template-template-homepage-php #columns p a,
		body.page-template-template-homepage-php #blog .blog-post a.more {
			border-bottom-color: '.esc_html( $nora_accent ).';
			}
			
		::selection,
		.mejs-time-current,
		.mejs-controls .mejs-horizontal-volume-slider .mejs-horizontal-volume-current,
		.nora_social_widget a:hover,
		#sidebar-footer .nora_social_widget a:hover,
		#sidebar-drawer .widget.nora_social_widget a:hover,
		.nora_project_widget .item a .overlay,
		.nora_project_widget .item a:hover .overlay { 
			background: '.esc_html( $nora_accent ).'; ?>;
			}

		a.btn,
		input[type="submit"],
		button.btn,
		.more-link,
		#header #toggle:hover,
		.flex-direction-nav a:hover,
		body.page-template-template-contact-php #contact-form input[type="submit"] {
			background-color: '.esc_html( $nora_accent ).';
		}

		#content article .entry-content blockquote {
			border-left-color: '.esc_html( $nora_accent ).';
		} ';

 }
